packages:
  - packages/*
  - examples/*

catalog:
  '@biomejs/biome': ^2.2.2
  '@effect/language-service': ^0.36.0
  '@effect/platform': ^0.90.6
  '@types/node': ^22.18.0
  effect: ^3.17.9
  esbuild: ^0.23.1
  tsup: ^8.5.0

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
