packages:
  - packages/*
  - examples/*
  - scripts

catalog:
  '@biomejs/biome': ^2.2.2
  '@effect/cli': ^0.69.2
  '@effect/language-service': ^0.37.0
  '@effect/platform-node-shared': ^0.49.0
  '@effect/platform-node': ^0.96.1
  '@effect/platform': ^0.90.6
  '@types/aws-lambda': ^8.10.152
  '@types/node': ^22.18.0
  aws-cdk-lib: ^2.214.0
  constructs: ^10.4.2
  dotenv-cli: ^10.0.0
  dotenv: ^17.2.1
  effect: ^3.17.10
  esbuild: ^0.25.9
  tsup: ^8.5.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - aws-sdk
  - esbuild
  - msgpackr-extract
